# Generated by Django 5.0.2 on 2024-03-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_pc', models.CharField(max_length=20)),
                ('date_pc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('raison_sociale', models.CharField(max_length=100)),
                ('tel_tax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nif', models.CharField(max_length=20)),
                ('numero_rs', models.CharField(max_length=20)),
                ('numero_bt_camion', models.CharField(max_length=20)),
            ],
        ),
    ]
