# Generated by Django 5.0.2 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
