# Generated by Django 5.0.2 on 2024-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_chauffeur_username_transporteur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
