# Generated by Django 5.0.2 on 2024-04-21 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0003_alter_chauffeur_username_alter_transporteur_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteneur', models.CharField(max_length=50)),
                ('reference_transport', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('reserve', 'Réservé'), ('libre', 'Libre')], max_length=50)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.chauffeur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
