# Generated by Django 5.0.2 on 2024-04-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='chauffeur',
        ),
        migrations.AddField(
            model_name='reservation',
            name='terminal',
            field=models.CharField(default='teract-best', max_length=50),
        ),
    ]
