# Generated by Django 5.0.6 on 2024-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='conteneur',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reference_transport',
        ),
        migrations.AddField(
            model_name='reservation',
            name='container',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='operation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='terminal',
            field=models.CharField(max_length=255),
        ),
    ]
