# Generated by Django 5.0.6 on 2024-06-21 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_timeslot_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='terminal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
